# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PriceTracker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTab = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.mainTab.setObjectName("mainTab")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.analysisTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 1281, 701))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.nutritionTab = QtWidgets.QTabWidget(self.widget)
        self.nutritionTab.setGeometry(QtCore.QRect(0, 160, 1270, 521))
        self.nutritionTab.setObjectName("nutritionTab")
        self.graphTab = QtWidgets.QWidget()
        self.graphTab.setObjectName("graphTab")
        self.exportImageBtn = QtWidgets.QPushButton(self.graphTab)
        self.exportImageBtn.setGeometry(QtCore.QRect(1228, 0, 36, 35))
        self.exportImageBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("export-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportImageBtn.setIcon(icon)
        self.exportImageBtn.setObjectName("exportImageBtn")
        self.visBox = QtWidgets.QWidget(self.graphTab)
        self.visBox.setGeometry(QtCore.QRect(0, 4, 1228, 491))
        self.visBox.setObjectName("visBox")
        self.nutritionTab.addTab(self.graphTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.dataTable = QtWidgets.QTableWidget(self.dataTab)
        self.dataTable.setGeometry(QtCore.QRect(0, 0, 1228, 521))
        self.dataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(0)
        self.dataTable.setRowCount(0)
        self.dataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.dataTable.horizontalHeader().setSortIndicatorShown(False)
        self.exportDataBtn = QtWidgets.QPushButton(self.dataTab)
        self.exportDataBtn.setGeometry(QtCore.QRect(1228, 0, 36, 35))
        self.exportDataBtn.setText("")
        self.exportDataBtn.setIcon(icon)
        self.exportDataBtn.setObjectName("exportDataBtn")
        self.nutritionTab.addTab(self.dataTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.nutritionTable = QtWidgets.QTableWidget(self.tab)
        self.nutritionTable.setGeometry(QtCore.QRect(0, 0, 1228, 501))
        self.nutritionTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nutritionTable.setAlternatingRowColors(True)
        self.nutritionTable.setObjectName("nutritionTable")
        self.nutritionTable.setColumnCount(0)
        self.nutritionTable.setRowCount(0)
        self.nutritionTable.horizontalHeader().setCascadingSectionResizes(False)
        self.nutritionTable.horizontalHeader().setSortIndicatorShown(False)
        self.exportNutDataBtn = QtWidgets.QPushButton(self.tab)
        self.exportNutDataBtn.setGeometry(QtCore.QRect(1228, 0, 36, 35))
        self.exportNutDataBtn.setText("")
        self.exportNutDataBtn.setIcon(icon)
        self.exportNutDataBtn.setObjectName("exportNutDataBtn")
        self.nutritionTab.addTab(self.tab, "")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(610, 10, 661, 151))
        self.groupBox.setObjectName("groupBox")
        self.itemList = QtWidgets.QListWidget(self.groupBox)
        self.itemList.setGeometry(QtCore.QRect(0, 20, 661, 131))
        self.itemList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.itemList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.itemList.setObjectName("itemList")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 601, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.fromDateEdit = QtWidgets.QDateEdit(self.groupBox_2)
        self.fromDateEdit.setGeometry(QtCore.QRect(80, 110, 141, 30))
        self.fromDateEdit.setCalendarPopup(True)
        self.fromDateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.fromDateEdit.setObjectName("fromDateEdit")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 30))
        self.label.setObjectName("label")
        self.brandLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.brandLineEdit.setGeometry(QtCore.QRect(80, 30, 181, 30))
        self.brandLineEdit.setClearButtonEnabled(True)
        self.brandLineEdit.setObjectName("brandLineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 47, 30))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(270, 110, 51, 30))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 47, 30))
        self.label_5.setObjectName("label_5")
        self.toDateEdit = QtWidgets.QDateEdit(self.groupBox_2)
        self.toDateEdit.setGeometry(QtCore.QRect(320, 110, 121, 30))
        self.toDateEdit.setCalendarPopup(True)
        self.toDateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.toDateEdit.setObjectName("toDateEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 101, 30))
        self.label_2.setObjectName("label_2")
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameLineEdit.setGeometry(QtCore.QRect(320, 30, 161, 30))
        self.nameLineEdit.setClearButtonEnabled(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.searchProductButton = QtWidgets.QPushButton(self.groupBox_2)
        self.searchProductButton.setGeometry(QtCore.QRect(511, 70, 81, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchProductButton.setIcon(icon1)
        self.searchProductButton.setCheckable(False)
        self.searchProductButton.setObjectName("searchProductButton")
        self.packSizeLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.packSizeLineEdit.setGeometry(QtCore.QRect(80, 70, 141, 30))
        self.packSizeLineEdit.setClearButtonEnabled(True)
        self.packSizeLineEdit.setObjectName("packSizeLineEdit")
        self.reportButton = QtWidgets.QPushButton(self.groupBox_2)
        self.reportButton.setGeometry(QtCore.QRect(510, 110, 81, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportButton.setIcon(icon2)
        self.reportButton.setObjectName("reportButton")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(264, 70, 47, 30))
        self.label_8.setObjectName("label_8")
        self.categoryLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.categoryLineEdit.setGeometry(QtCore.QRect(320, 70, 121, 30))
        self.categoryLineEdit.setClearButtonEnabled(True)
        self.categoryLineEdit.setObjectName("categoryLineEdit")
        self.verticalLayout_2.addWidget(self.widget)
        self.mainTab.addTab(self.analysisTab, "")
        self.dataImportTab = QtWidgets.QWidget()
        self.dataImportTab.setObjectName("dataImportTab")
        self.dataImportGB = QtWidgets.QGroupBox(self.dataImportTab)
        self.dataImportGB.setGeometry(QtCore.QRect(10, 10, 601, 121))
        self.dataImportGB.setObjectName("dataImportGB")
        self.checkBox = QtWidgets.QCheckBox(self.dataImportGB)
        self.checkBox.setGeometry(QtCore.QRect(20, 75, 121, 25))
        self.checkBox.setObjectName("checkBox")
        self.newDataFileLe = QtWidgets.QLineEdit(self.dataImportGB)
        self.newDataFileLe.setGeometry(QtCore.QRect(70, 40, 441, 25))
        self.newDataFileLe.setObjectName("newDataFileLe")
        self.label_6 = QtWidgets.QLabel(self.dataImportGB)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 111, 25))
        self.label_6.setObjectName("label_6")
        self.openDataFileBtn = QtWidgets.QPushButton(self.dataImportGB)
        self.openDataFileBtn.setGeometry(QtCore.QRect(520, 40, 75, 25))
        self.openDataFileBtn.setObjectName("openDataFileBtn")
        self.loadDataFileBtn = QtWidgets.QPushButton(self.dataImportGB)
        self.loadDataFileBtn.setGeometry(QtCore.QRect(520, 75, 75, 25))
        self.loadDataFileBtn.setObjectName("loadDataFileBtn")
        self.dataImportGB_2 = QtWidgets.QGroupBox(self.dataImportTab)
        self.dataImportGB_2.setGeometry(QtCore.QRect(10, 130, 601, 121))
        self.dataImportGB_2.setObjectName("dataImportGB_2")
        self.testRunAdditionCb = QtWidgets.QCheckBox(self.dataImportGB_2)
        self.testRunAdditionCb.setGeometry(QtCore.QRect(20, 75, 121, 25))
        self.testRunAdditionCb.setObjectName("testRunAdditionCb")
        self.additionalPriceDataFileLe = QtWidgets.QLineEdit(self.dataImportGB_2)
        self.additionalPriceDataFileLe.setGeometry(QtCore.QRect(70, 40, 441, 25))
        self.additionalPriceDataFileLe.setObjectName("additionalPriceDataFileLe")
        self.label_7 = QtWidgets.QLabel(self.dataImportGB_2)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 111, 25))
        self.label_7.setObjectName("label_7")
        self.openAddedDataFileBtn = QtWidgets.QPushButton(self.dataImportGB_2)
        self.openAddedDataFileBtn.setGeometry(QtCore.QRect(520, 40, 75, 25))
        self.openAddedDataFileBtn.setObjectName("openAddedDataFileBtn")
        self.loadAddedDataFileBtn = QtWidgets.QPushButton(self.dataImportGB_2)
        self.loadAddedDataFileBtn.setGeometry(QtCore.QRect(520, 75, 75, 25))
        self.loadAddedDataFileBtn.setObjectName("loadAddedDataFileBtn")
        self.mainTab.addTab(self.dataImportTab, "")
        self.verticalLayout.addWidget(self.mainTab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.nutritionTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mainTab, self.brandLineEdit)
        MainWindow.setTabOrder(self.brandLineEdit, self.nameLineEdit)
        MainWindow.setTabOrder(self.nameLineEdit, self.packSizeLineEdit)
        MainWindow.setTabOrder(self.packSizeLineEdit, self.categoryLineEdit)
        MainWindow.setTabOrder(self.categoryLineEdit, self.searchProductButton)
        MainWindow.setTabOrder(self.searchProductButton, self.fromDateEdit)
        MainWindow.setTabOrder(self.fromDateEdit, self.toDateEdit)
        MainWindow.setTabOrder(self.toDateEdit, self.reportButton)
        MainWindow.setTabOrder(self.reportButton, self.itemList)
        MainWindow.setTabOrder(self.itemList, self.nutritionTab)
        MainWindow.setTabOrder(self.nutritionTab, self.exportImageBtn)
        MainWindow.setTabOrder(self.exportImageBtn, self.exportDataBtn)
        MainWindow.setTabOrder(self.exportDataBtn, self.exportNutDataBtn)
        MainWindow.setTabOrder(self.exportNutDataBtn, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.newDataFileLe)
        MainWindow.setTabOrder(self.newDataFileLe, self.openDataFileBtn)
        MainWindow.setTabOrder(self.openDataFileBtn, self.loadDataFileBtn)
        MainWindow.setTabOrder(self.loadDataFileBtn, self.testRunAdditionCb)
        MainWindow.setTabOrder(self.testRunAdditionCb, self.additionalPriceDataFileLe)
        MainWindow.setTabOrder(self.additionalPriceDataFileLe, self.openAddedDataFileBtn)
        MainWindow.setTabOrder(self.openAddedDataFileBtn, self.loadAddedDataFileBtn)
        MainWindow.setTabOrder(self.loadAddedDataFileBtn, self.nutritionTable)
        MainWindow.setTabOrder(self.nutritionTable, self.dataTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Price Tracker"))
        self.exportImageBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Export Image</p></body></html>"))
        self.nutritionTab.setTabText(self.nutritionTab.indexOf(self.graphTab), _translate("MainWindow", "Graph"))
        self.dataTable.setSortingEnabled(False)
        self.exportDataBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Export Data</p></body></html>"))
        self.nutritionTab.setTabText(self.nutritionTab.indexOf(self.dataTab), _translate("MainWindow", "Data"))
        self.nutritionTable.setSortingEnabled(False)
        self.exportNutDataBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Export Data</p></body></html>"))
        self.nutritionTab.setTabText(self.nutritionTab.indexOf(self.tab), _translate("MainWindow", "Nutrition Info"))
        self.groupBox.setTitle(_translate("MainWindow", "Search Results: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search for products:"))
        self.fromDateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label.setText(_translate("MainWindow", "Brand :"))
        self.brandLineEdit.setPlaceholderText(_translate("MainWindow", " Product Brand"))
        self.label_4.setText(_translate("MainWindow", "Name :"))
        self.label_3.setText(_translate("MainWindow", "To date : "))
        self.label_5.setText(_translate("MainWindow", "Pack Size: "))
        self.toDateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_2.setText(_translate("MainWindow", "From date : "))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", " Product Name"))
        self.searchProductButton.setText(_translate("MainWindow", "Search"))
        self.searchProductButton.setShortcut(_translate("MainWindow", "Alt+S"))
        self.packSizeLineEdit.setPlaceholderText(_translate("MainWindow", " Pack Size"))
        self.reportButton.setText(_translate("MainWindow", "Report"))
        self.reportButton.setShortcut(_translate("MainWindow", "Alt+R"))
        self.label_8.setText(_translate("MainWindow", "Category:"))
        self.categoryLineEdit.setPlaceholderText(_translate("MainWindow", "Category"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.dataImportGB.setTitle(_translate("MainWindow", "Import New Data"))
        self.checkBox.setText(_translate("MainWindow", "Run a test only "))
        self.label_6.setText(_translate("MainWindow", "Data file:"))
        self.openDataFileBtn.setText(_translate("MainWindow", "Open"))
        self.loadDataFileBtn.setText(_translate("MainWindow", "Load"))
        self.dataImportGB_2.setTitle(_translate("MainWindow", "Import Additional Price Data"))
        self.testRunAdditionCb.setText(_translate("MainWindow", "Run a test only "))
        self.label_7.setText(_translate("MainWindow", "Data file:"))
        self.openAddedDataFileBtn.setText(_translate("MainWindow", "Open"))
        self.loadAddedDataFileBtn.setText(_translate("MainWindow", "Load"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.dataImportTab), _translate("MainWindow", "Data Import"))

